### ISSUE TITLE
Postgresql sorting

### ISSUE THREAD

**Issue by mhenrixon** [stefankroes/ancestry#131]
Ancestry is generating the following sort statement

``` sql
ORDER BY (case when pages.ancestry is null then 0 else 1 end), pages.ancestry, position;
```

This is really ineffective, for postgresql that should be 

``` sql
ORDER BY pages.ancestry, position;
```

The reason being that postgres has build in support for nulls sorting with a default option of `NULLS FIRST`.

**Comment by brendon** [comment]
This is the same for MySQL. I was wondering which database requires this query? I've had feedback that it's extra slow.

**Comment by brendon** [comment]
Just wanted to bump this one. Could we get some insight into the `case` statement? What database server requires this?

**Comment by kbrock** [comment]
Brandon, if you search the web, this case statement is the standard way to ensure the nulls come first in a sort.

To be honest, our logic no longer requires the records to be sorted, but our public interface clearly states the sorting order. Not sure if there is a way to skip the sorting all together.

1. Postgres needs `NULLS FIRST` option.
2. Research what Mysql needs to return nulls first. Possibly `IS NULL` or maybe it is nulls first by default.
3. Research what sorting configuration exist to see if Mysql or Postgres can change the order of nulls (first or last). -- I'm hoping there are none so we don't have to be concerned with this
4. Research rails code that determines database type without requiring a connection open to the database. possibly looking at configuration directly?
5. Move database specific logic into a mixin. `include` this in `has_ancestry`.

Steps 4 and 5 are not required, but give us more freedom to make database specific changes.

**Comment by brendon** [comment]
Thanks @kbrock :) I've done a bit of quick research:

* Postgresql:
    > The NULLS FIRST and NULLS LAST options can be used to determine whether nulls appear before or after non-null values in the sort ordering. By default, null values sort as if larger than any non-null value; that is, NULLS FIRST is the default for DESC order, and NULLS LAST otherwise.

* MySQL:
    > When doing an ORDER BY, NULL values are presented first if you do ORDER BY ... ASC and last if you do ORDER BY ... DESC.

* SQLite:
    > SQLite processes NULL value differently. A row with a NULL value is higher than rows with regular values in ascending order, and it is reversed for descending order.

You are right in that Postgres needs that option specified as it seems to operate the opposite way to MySQL. MySQL needs no extra option provided we don't specify `DESC` which we don't. The same applies to SQLite.

To answer 3: Postgresql doesn't have any configuration options. MySQL doesn't appear to have that option either, though I can't find anyone saying it doesn't.

For 4: We can access `ActiveRecord::Base.configurations[Rails.env]['adapter']` to get the adapter used. I'm pretty sure this can be done without connecting first.

Number 5 sounds like a good idea. At this stage it looks like only Postgresql requires the tweak.

I hope that helps. Let me know if you need help with the next steps :)

**Comment by brendon** [comment]
Just pinging this one again. I'm keen to do a PR if you want, though I'll need some guidance on number 5.

**Comment by kbrock** [comment]
@brendon Let me share how far I've gotten. I've lost some steam because I didn't feel I had a good testbed for proving the performance of the various approaches or pointing out regressions.

All of the code used to be in `has_ancestry.rb` - I'd like for it just to be logic that decides which mixin was necessary.

`materialized_path.rb` is the parent class (?) that assumes there is an `ancestry` column. I was thinking there would be a `tree_path`, `ancestry_id[]`, and maybe closure tree version of this. Possibly even have sub classes for each of those for db vendor. Currently, `has_ancestry.rb` has a few of those db checks.
`instance_methods.rb` is the part that takes care of ancestry logic itself.

I've found it hard to separate by those guidelines. My views were probably unrealistic.

So option 5 would either be a subclass of materialized_path or a mixin that works in conjunction.

Hmm. Sorry. Text too long and not enough time to shorten.
Does this get you started, or you have other questions?

**Comment by brendon** [comment]
Stale? :)
