### ISSUE TITLE
Any reason why `root` is not a `has_one` relationship?

### ISSUE THREAD

**Issue by apneadiving** [stefankroes/ancestry#203]
Could be very convenient in order to use `includes`.

Thanks!

**Comment by sebastian-zm** [comment]
My English is not good, but I really think this could be a good idea, so please bear with me.

I wonder if something like this could be added with has_ancestry (untested code, just something that may work with a few changes):

```Ruby
has_one :root, ->(this_instance) { unscope(where: :root_id).where(id: this_instance.root_id) }, class_name: self.class.ancestry_base_class.to_s, inverse_of: :descendants
```
This would not work as is because descendants does not include the root node (which is the root of itself). However, root would ideally have an inverse.

Other methods that have an inverse are simpler to adapt, so I put them here as an example:

```Ruby
has_one :parent, ->(this_instance) { this_instance.has_parent? ? unscope(where: :root_id).where(id: this_instance.parent_id) : unscope(where: :root_id).where(Arel.sql('1=0')) }, class_name: self.class.ancestry_base_class.to_s, inverse_of: :children

has_many :children, ->(this_instance) { unscope(where: :root_id).where(ancestry: "#{this_instance.ancestry}#{this_instance.id}/") }, class_name: self.class.ancestry_base_class.to_s, inverse_of: :parent
```

What I am doing there:
  * `class_name` makes `has_one`/`has_many` look for the parent/children in its own model
  * `unscope` undoes the where that Rails makes
  * the scope selects the correct instances
  * `inverse_of` allows better handling of instances before persisting them

Benefit:

Such a refactor would allow using Rails's inverse of niceties, and also unpersisted parents, I think.

Con:

It could be considered bad style, but maybe not if someone with more experience than me rewrites this.
