### ISSUE TITLE
Running db:migrate on pulled git commit returns: undefined method 'ancestry'

### ISSUE THREAD

**Issue by Folkman** [stefankroes/ancestry#288]
I installed ancestry by adding it to the Gemfile and running `bundle`, creating and running the migrations, then adding `has_ancestry` to the model.  After implementing it, I made a commit and pushed it.

Co-worker pulls the changes.  Runs `bundle`, runs `db:migrate` and gets this error:

`undefined method 'ancestry' for #<ModelName:0x007fa7b6371260>`

He was able to fix this by temporarily removing `has_ancestry` from the model, which expected the `ancestry` column to exist already, and then running the migrations before adding it back.  Since the column did not exist prior to the migrations, the app could not be loaded in order to run the migrations.

**Comment by kbrock** [comment]
I'm guessing you access the Active Record model from your migration.

This tends to cause all sorts of problems with areas other than ancestry, like issues when you change validations and others.

To solve this, most people either introduce a temporary class to the migration or just use pure sql.

**Comment by Folkman** [comment]
Yes, in a later migration, I was accessing the model to update existing records.  So it seems more of an issue with the later migrations in Rails not picking up on the fact that the column was created already.  I'll go ahead and close this issue.

**Comment by kbrock** [comment]
@Folkman I had a migration that converted from `parent_id` style to `ancestry`.

Ended up having to reimplement part of ancestry because my team has a very strict policy around using models. It was frustrating and tricky to say the least. Tried a number of ways of incorporating ancestry in the migration. ended up giving up.

I'll keep this in the back of my mind. May have an epiphany and solve it for both of us
