### ISSUE TITLE
IrreversibleOrderError

### ISSUE THREAD

**Issue by stricte** [stefankroes/ancestry#312]
In Rails 5.0.0.1

Sth like this `child.ancestors.last` produces this:

> Finding a last element by loading the relation when SQL ORDER can not be reversed is deprecated. Rails 5.1 will raise ActiveRecord::IrreversibleOrderError in this case. Please call `to_a.last` if you still want to load the relation.

Of course i don't want to fetch all relation to get its last record.

**Comment by kbrock** [comment]
Ok, so the problem is `child.ancestors.reverse` does not work?

**Comment by stricte** [comment]
Hi
`child.ancestors.reverse` work because it work on fetched array. However `child.ancestors.reverse_order` do not work because `coalesce("places"."ancestry", '')` is not reversible. For now, rails 5.0.0, its ok, but in 5.1 we will have problem.

I use it because i need to take nearest parent which meets certain conditions, i.e. `ancestors.where(do_something: true).last`

**Comment by kbrock** [comment]
I'm wondering why we have the ordering the way we do.

will try and see if there is a different way of approaching this

**Comment by simonc** [comment]
The problem originates from items with a `NULL` ancestry. They're listed first by default.

There are several ways to work around that:
1. usually `NULLS LAST` but it would end-up with an `IrreversibleOrderError` too
2. `.reorder("(ancetry IS NOT NULL)", :ancestry)`
3. `.first(N).reverse`

I chose option 2 for it was the most explicit. Maybe a good idea could be to avoid `NULL` ancestry at all or something like that 😕

**Comment by kbrock** [comment]
@simonc Items with `null` ancestry are the root nodes. So it makes sense that they would come first.

I have been throwing around the idea of not sorting at all in any queries. Before, we had to sort to get those values first. Now, we build the trees from data in any order, so that is no longer necessary.

But I suppose, that will not help you in this case.

So you are suggesting dropping the `coalesce("places"."ancestry", '')` and instead storing `ancestry = ''` right?

**Comment by simonc** [comment]
@kbrock Yes I am aware but the problem is that they still come first when you ask for the `.last(3)` for instance.

Regarding the ordering and storing `''` that might indeed do the trick but that would imply a breaking-change and thus a new major version (find by me).

We may have to consider the memory impact for large databases though. I have no idea how big an impact it is.
