### ISSUE TITLE
Is it possible create a full Hash Tree at once?

### ISSUE THREAD

**Issue by wbotelhos** [stefankroes/ancestry#375]
Hi, first all, thanks for this great gem.

I would like to create a `hash_tree`, like [Closure Tree does](https://github.com/ClosureTree/closure_tree#nested-hashes).
With Ancestry, I need to load first all root elements and them map each one to be possible call `subtree` and so `arrange`.

Is there any way to call `arrange` over a criteria collection to avoid N + 1?

Here is my question there about what I'm trying to do: https://github.com/ClosureTree/closure_tree/issues/295

**Comment by kbrock** [comment]
Hi @wbotelhos 

You want to do `Model.subtree_of(Model.roots)`

But yes, it will load the roots into memory and then do an N+1.

The issue is in https://github.com/stefankroes/ancestry/blob/master/lib/ancestry/materialized_path.rb#L43


Currently, the children is a function and not a scope.
I'm working on converting a number of these methods into scopes - so you can do that.
But, to be honest the work is slow going (a low priority) and not really possible.

Have you tried `Model.arrange_nodes(Model.all)` ?
(not perfect, but possibly will work for you

**Comment by kbrock** [comment]
Issue has gone stale.

`arrange_nodes` will work over a collection. Current limitation is the full trees need to be present
