### ISSUE TITLE
Soft delete option?

### ISSUE THREAD

**Issue by MSCAU** [stefankroes/ancestry#416]
What do you recommend for soft deletion of ancestry records?

:orphan_strategy is great but I have a tree of comments and don't want to **destroy** when a user deletes his / her comment. I prefer to keep that comment and its descendants in the database.

**Comment by kbrock** [comment]
Hello @MSCAU

I haven't had much experience with soft delete and ancestry. I've tended to roll my own, but there are a number to choose from.

I am curious how this would work.

```
d.path = /a/b/c/d
b.soft_delete!
d.path == /a/c/d
```
Or does `d.path == /a/b/c/d` and record `b` never comes back in query / never goes to ancestry arrange.

I think we've ironed out edge cases with default_scopes (which soft deletes tend to use), but 3.0.4 is still ironing out incomplete ancestry trees.

The current issue:
```ruby
Model.arrange(Model.all.undeleted)
{
  a => {},
  c => {d => {}}
}
```

when you really want:

```ruby
{a => {c => { d => }}}
```

Since c's parent is b, it is not able to guess where it belongs in the tree.

Please check in again once you get a little further. I'd like to watch your progress.

**Comment by MSCAU** [comment]
Thanks, @kbrock. I must admit it's not an easy problem. It's also not a major feature of my app so I'm going to restrict deleting to leaf nodes only. If that changes - and I don't expect that in the next 6 months - I may come back to you.

**Comment by kbrock** [comment]
@MSCAU please do

By that time, hopefully you will have some good ideas on how to handle the middle nodes
