### ISSUE TITLE
its not working with rails 6

### ISSUE THREAD

**Issue by Faisal-nfl** [stefankroes/ancestry#465]
your docs says 
**Ancestry 4.0 only supports rails 5.0 and higher**

but latest version is 3.0.7 and its not working with rails 6
saying **undefined has_ancestry**

**Comment by kbrock** [comment]
Hi @Faisal-nfl 

We're testing against rails 6.0 ==> https://github.com/stefankroes/ancestry/blob/master/.travis.yml#L19
And it has been working for many other contributors.

Looking at your error, it looks more like a usage error rather than a rails 6.0 issue.

Does it work if you point bundler at master?

**Comment by Faisal-nfl** [comment]
yes, it seems that it was on my side.

**Comment by swapnali-techverito** [comment]
Its not working on our end. We are getting same issue in rails 6.
Urgent help appreciated.

**Comment by Faisal-nfl** [comment]
it was nothing.
next day when I started my PC it was working
