### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by b-ouinten** [stefankroes/ancestry#508]
Hi !

First of all, I intend to thank you for the gem, it helped me a lot. However, I am wondering if there is a pretty way to return only the deeper nodes. I tried the following : root.descendants.to_a.delete_if { |node| node.has_children? } but I think that isn't the efficient way as it took a long time to complete the process. I did a test with a tree containing 10000 nodes.

Thank you in advance.

**Comment by kevinluo201** [comment]
I think this the feature we all want, lol
I saw a couple of solutions in this repo by composing a great SQL, for example [link](https://github.com/stefankroes/ancestry/pull/246#issuecomment-193688104), but they all have some constraints like the SQL is only valid in MySQL or PG

**Comment by kbrock** [comment]
I'm ok with pg or mysql specific changes.
I tried to put in place a pattern that allows us to have database specific changes.
at mixin time you don't have access to the database so we need to ask the user to take on that responsibility by passing it in or something like that.

its just the way we define these scopes and attributes that is troublesome, especially with rails 6.
And the to_node code at the beginning has issues.

I have a branch that introduces a new path format with a slash at the beginning and the end. this gets rid of the or and fixes a few things but I didn't get much performance differences.

I have a branch that stores with arrays which is pg only but has promise.

In the end I feel extracting the serialization format from our code makes sense.  this would leverage the rails attribute api.

Still trying to figure out the full implications of this approach as it looks like it allows us to even have multiple parent trees (only one parent chain per tree, but multiple ancestry columns)

Not sure how clean the changes would be, especially since people tend to monkey patch this code a bunch.

**Comment by kbrock** [comment]
sorry - I had written that 11 days ago but hadn't clicked the submit button

**Comment by kbrock** [comment]
lets keep the discussion over in #246
