### ISSUE TITLE
using has_ancestry in subclass throws error

### ISSUE THREAD

**Issue by jtromp** [stefankroes/ancestry#87]
When I add "has_ancestry" in a subclass of another class (that inherites from ActiveRecord:Base), an error is thrown in development mode:

Mysql::Error: Table 'AUTHORABLE.groups' doesn't exist: SHOW FIELDS FROM `groups`

The class hierarchy in this case is: ActiveRecord::Base > Authorable > Group

The Group class has "has_ancestry" defined. Is this expected behaviour, or is there a solution? I could not find anything related to this in the documentation.

**Comment by kbrock** [comment]
Hello @jtromp 

Not sure if you have github alerts turned on, and you probably moved on from this application a long time ago.

But I am hoping you might remember a little bit about this application from 10+ years ago.

Do you remember if you liked how this model turned out? Can you guess if putting `has_ancestry` at the top level would have worked out just as well?

I'm trying to understand if this is an important feature to keep, and thought I would make a long shot in reaching out to you.

Thanks,
Keenan
